config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :addresses
  resources :customers do
    resources :customer_addresses
  end  
  resources :invoices do
    resources :payments
  end  
  
  devise_for :users, path_prefix: 'auth'
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :customer
    has_many :payments, dependent: :delete_all

    validates :num, :date_invoice, presence: true

    def invoice_data
        "Num: #{num}| Date: #{date_invoice}" 
    end    
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
    @payments = @invoice.payments
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:customer_id, :num, :date_invoice, :sum, :comment)
    end
end

app/views/invoices/_form.html.erb
<%= bootstrap_form_with(model: invoice, local: true) do |form| %>

  <div class="field">
    <%= form.collection_select(:customer_id, Customer.all, :id, :full_name, prompt:true) %>
  </div>

  <div class="field">
    <%= form.text_field :num %>
  </div>

  <div class="field">
    <%= form.date_select :date_invoice, prompt:true %>
  </div>

  <div class="field">
    <%= form.text_field :sum %>
  </div>

  <div class="field">
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Num</th>
      <th>Date Invoice</th>
      <th>Sum</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.customer.full_name %></td>
        <td><%= invoice.num %></td>
        <td><%= invoice.date_invoice %></td>
        <td><%= invoice.sum %></td>
        <td><%= invoice.comment %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @invoice.customer&.full_name %>
</p>

<p>
  <strong>Num:</strong>
  <%= @invoice.num %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date_invoice %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @invoice.sum %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @invoice.comment %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Add Payment', new_invoice_payment_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>
<br /><br />
<div class="card">
    <div class="card-header">
    Invoice <%= @invoice.invoice_data %> payments
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
            <tr>
              <th scope="col">Num</th>
              <th scope="col">Date</th>
              <th scope="col">Sum</th>
              <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody id="channelTableItems">
          <%= render partial: 'payments/table_item', collection: @payments  %>
        </tbody>
      </table>
    </div>
</div>