config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :addresses
  resources :customers do
    resources :customer_addresses
  end  
  resources :invoices do
    resources :payments
  end  
  
  devise_for :users, path_prefix: 'auth'
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :invoice
    
    validates :num, :date_pay, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_invoice
  before_action :set_payment, only: %i[ show edit update destroy ]
  

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @invoice, notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to @invoice, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def set_invoice
      @invoice = Invoice.find(params[:invoice_id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:invoice_id, :num, :date_pay, :sum, :comment)
    end
end

app/views/payments/_form.html.erb
<%= bootstrap_form_with(model: [@invoice, payment], local: true) do |form| %>

  <%= form.hidden_field :invoice_id, value: @invoice.id %>

  <div class="field">
    <%= @invoice.invoice_data  %>
  </div>

  <div class="field">
    <%= form.text_field :num %>
  </div>

  <div class="field">
    <%= form.date_select :date_pay, prompt:true %>
  </div>

  <div class="field">
    <%= form.text_field :sum %>
  </div>

  <div class="field">
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_table_item.html.erb
<tr class="payment_item_<%= table_item.id %>">
  <%= content_tag :td, table_item.num %>
  <%= content_tag :td, table_item.date_pay %>
  <%= content_tag :td, table_item.sum %>
  <td>
    <%= link_to 'edit', edit_invoice_payment_path(@invoice, table_item), class: 'btn btn-default' %><br />
    <%= link_to 'delete', invoice_payment_path(@invoice, table_item), method: 'delete', data: {confirm: "Are you sure?"}, class: 'btn btn-default' %>
  </td>
</tr>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', invoice_path(@invoice) %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Invoise</th>
      <th>Num</th>
      <th>Date pay</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.invoice.num %></td>
        <td><%= payment.num %></td>
        <td><%= payment.date_pay %></td>
        <td><%= payment.comment %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', invoice_path(@invoice) %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>References:</strong>
  <%= @payment.references %>
</p>

<p>
  <strong>Num:</strong>
  <%= @payment.num %>
</p>

<p>
  <strong>Date pay:</strong>
  <%= @payment.date_pay %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @payment.comment %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>