config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :addresses
  resources :customers do
    resources :customer_addresses
  end  
  resources :invoices do
    resources :payments
  end  
  
  devise_for :users, path_prefix: 'auth'
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Billing</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= invoices_path %>">Invoices</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= customers_path %>">Customers</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= addresses_path %>">Addresses</a>
        </li>
    </ul>
  </div>
  <ul class="nav navbar-nav align-items-center ml-auto">
    <span class="user-name font-weight-bolder"><%= current_user.name %></span>
    <li class="c-header-nav-item dropdown">
      <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <div class="c-avatar">
          <% if current_user.avatar.present? %>
            <%= image_tag current_user.avatar, height: 50, width: 50, class: 'c-avatar-img', alt: current_user.email %>
          <% else %>
            <%= image_tag user_gravatar_url(current_user), class: 'c-avatar-img', alt: current_user.email %>
          <% end %>  
        </div>
      </a>
      <div class="dropdown-menu dropdown-menu-right pt-0">
          <a class="dropdown-item" href="<%= edit_user_path(current_user) %>">Accout</a>
          <a class="dropdown-item" href="<%= destroy_user_session_path %>">Sign out</a>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMidDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu' if user_signed_in? %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>